// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqqhjlrajqoazatkkqqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxcWhqbHJhanFvYXphdGtrcXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzQ0MDQsImV4cCI6MjA3Mzc1MDQwNH0._4MjMNz65UNNWO1asnGzOnFc1MtuFB1zWU3r8lkF3kA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});